### PR TITLE
Add instances for ShortByteString

### PR DESCRIPTION
**Pull request by cocreature**

### CODE REVIEW

**Comment by phadej** [comment]
failure with `bytestring<0.10.4`

**Comment by cocreature** [comment]
Good catch, do you want me to raise the lower bound or use CPP? `bytestring-0.10.4` was released in 2013 so a lower bound seems pretty reasonable.

**Comment by phadej** [comment]
No, I want to support GHC-7.4. Please use CPP to guard instances.

**Comment by phadej** [comment]
additions to previous: this is testing package, I try to have as wide bounds as possible, so it can be used in all situations where one would expect to use QuickCheck (which also has support back to 7.4 IIRC)

**Comment by cocreature** [comment]
Alright, I’ve added the CPP.

**Comment by phadej** [comment]
Thanks!

**Pull request merged**
