### PR TITLE
Split instances

### PR DESCRIPTION
**Pull request by dfithian**
Split the instances into their respective buckets so that they can be imported as needed.

### CODE REVIEW

**Comment by phadej** [comment]
This is massive, thanks a lot!

I'll take a closer look soon, but LGTM so far

**Comment by dfithian** [comment]
Hey @phadej, any updates? Personally I was able to import this wholesale into my project and it all worked fine. Then I split it up and implemented my own Arbitrary Text. Obviously I don't use most of the instances though.

**Comment by dfithian** [comment]
@phadej Sorry to keep bugging you, anything I can do to help you test?

**Comment by phadej** [comment]
Thanks for the remindier. Looks good.

**Pull request merged**
